### ISSUE TITLE
Pokestops don't say what you received in the latest build.

### ISSUE THREAD

**Issue by Lynical** [Sen66/Pokemon-Go-Rocket-API#1]
The pokestops messages aren't saying what you've received from the pokestop.

**Comment by Sen66** [comment]
They are. But if the pokestop for example gives you no item nor xp it wont display it.
If you encounter that multiple times tell me please.

**Comment by Lynical** [comment]
@Sen66 http://prntscr.com/bw7fp3

I'm getting pokestops without giving me anything (according to the messages) all the time ;p

**Comment by Sen66** [comment]
Can you try using another location or keep it running for ~5minutes or something.
Mine also doesnt show me items always because there are none.

**Comment by Lynical** [comment]
I've been running it now for around 20 minutes or even longer and still no messages with what i've received from the pokestop.

I did use the other version from the other person and his did give the messages. ( same location )

I also always use this location as it's basically where all the shops are near me which is really good for pokemon.

Screenshot: http://prntscr.com/bw7jql

**Comment by Sen66** [comment]
thats very weird, my friends also use my version and it works for them. But I see you also have stuff from another version? is this true? maybe its because of this.

**Comment by Lynical** [comment]
Uhm I deleted the other version from 10 hours ago, that was made by your friend?

Maybe it only works in your region?

**Comment by Sen66** [comment]
You could tell me what features you have added. So I can test the compatibility with them and add it to my version.

**Comment by Lynical** [comment]
I haven't added anything, im using your version with everything default, but edited some value's.

example would be that i removed Pidgey from the unwanted list
i changed coordinates
i set the authentication thingy to google
i set the transfertype to leaveStrongest

and that's the only thing i changed.

**Comment by Sen66** [comment]
Would you post me your full code from Program.cs? Maybe pastebin?

**Comment by Lynical** [comment]
http://pastebin.com/m6Bj1SyK

expires in an hour.

**Comment by Lynical** [comment]
I hate when this shitty null reference error happens: http://prntscr.com/bw7tdn
do you know why it's happening?

**Comment by Sen66** [comment]
Removing the GoogleRefreshToken from the config should fix this problem.

**Comment by Lynical** [comment]
thanks it actually did <3

but still the pokestops aren't saying what im getting from them ,beside XP and the name of the pokestop.

**Comment by Sen66** [comment]
Try downloading my project again without merging it with others. If it still wont show the pokestop details tell me.

**Comment by Lynical** [comment]
your newest version has a error : http://prntscr.com/bw82fn

how do i fix it?

**Comment by Sen66** [comment]
Seems like an error in your doNotTransfer array. Have you changed anything?

**Comment by Lynical** [comment]
I changed this to http://prntscr.com/bw83t8

**Comment by Sen66** [comment]
The array cant be empty. Thanks for that bug. Put a pokemon in it to fix it. Ill fix the bug asap.

**Comment by Lynical** [comment]
oh okay thanks.

**Comment by Lynical** [comment]
Edit3: my berry settings are: http://prntscr.com/bw868y

so yeah it shouldn't be using 1 for all pokemons?

**Comment by Sen66** [comment]
Oh sorry, my mistake. Change Program.cs Line 221 to `if (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() < ClientSettings.RazzBerrySetting / 100)`
Add the "/ 100"

**Comment by BioMuell** [comment]
and change to 30 not 300
:p

**Comment by Lynical** [comment]
i did that and now this http://prntscr.com/bw87f5

and why would I change to 30 when I don't want pokemons lower then combat 300?

**Comment by BioMuell** [comment]
your settings is not CP but Capture Probability

**Comment by Sen66** [comment]
wut?

**Comment by Lynical** [comment]
http://prntscr.com/bw88ps

@Sen66

**Comment by Sen66** [comment]
I havent made the Transfer stuff :) But whats with the Razzberry stuff?

**Comment by Lynical** [comment]
It keeps using 1 rasberry everytime it catches a pokemon of any level and any rarity.

**Comment by Lynical** [comment]
@biomuell please get out of here, you're confusing me and probably @Sen66 

Im talking about something way different then what you're saying above.

**Comment by Lynical** [comment]
@Sen66 
it keeps using 1 rasberry for all pokemons im catching which is bugged?

**Comment by Sen66** [comment]
I think there is some missunderstanding here.
Razzberries have nothing to do with the transfer stuff.
RazzBerryMode can have 2 settings, "cp" and "probability". When cp is choosen you put in the cp at which CP of the Pokemon you want to use a RazzBerry. When you have probability you put a percentage in there for example "40". But `In the cp you can say at which CP of the Pokemon you want to use a RazzBerry` returns not between 0 and 100. It returns for example 0.4 so we need to divide our percentage by 100 at line 221 in Program.cs

Which mode are you using at which settings now?

**Comment by Lynical** [comment]
http://prntscr.com/bw8c00 these are my settings, if the catching probability is under 15% it should be using 1 rasberry to make it a bigger chance, but now instead of using it only at 15% it's using it at all the pokemons it's trying to catch.

**Comment by Sen66** [comment]
Did you put the "/100" at the line I told you?

**Comment by Lynical** [comment]
http://prntscr.com/bw8d9e

and now it's giving me this: http://prntscr.com/bw8de8

**Comment by Lynical** [comment]
and this bug too: http://prntscr.com/bw8j13


so you need to fix all these:

http://prntscr.com/bw8j13
http://prntscr.com/bw8d9e
http://prntscr.com/bw8de8

and the rasberry bug

If you have Skype It would be easier for me to report bugs to you if you'd like.

**Comment by Sen66** [comment]
![2016-07-22at20-25-23](https://cloud.githubusercontent.com/assets/5496231/17067098/722cd824-504a-11e6-85be-ae88de71241f.jpg)
Im also not getting the Item output at every location because there is none.
Mine isnt using raspberries at every pokemon on probability mode on 0.4 (I changed the configuration and will commit it asap) and the last error with the exception is something with Google.

**Comment by Lynical** [comment]
I don't have google refreshtoken though?
http://prntscr.com/bw8lz6

Do you mind telling me how i can clean my whole visual studio from all the old projects so it doesn't merge it into new projects etc?

( I'm a beginner programmer, studying C/C++ so yeah i don't know anything at all )

**Comment by Sen66** [comment]
The best way to use the github repos in visual studio is to open it via Source Control in Visual Studio(clone it)
And it stores the Google refresh token in some file called
![2016-07-22at20-31-54](https://cloud.githubusercontent.com/assets/5496231/17067290/5be10e9a-504b-11e6-9c4f-688e984f5e3a.jpg)
PokemonGo.RocketAPI.Console.exe.CONFIG when it doesnt run in vs 
PokemonGo.RocketAPI.Console.vshost.exe.CONFIG when it runs in vs

**Comment by Lynical** [comment]
Oh okay thanks.

you still need to fix all these:

http://prntscr.com/bw8d9e
http://prntscr.com/bw8de8
http://prntscr.com/bw8j13

Like 75% atleast of what it's trying to catch is now going away instead of being caught.
and the message of it throwing a pokeball and catching it etc is also gone now?

**Comment by Sen66** [comment]
First screenshot should be fixed as im no longer using that math.
Third sc I dont see a bug. Just some unlucky time :^).

**Comment by Lynical** [comment]
Third, it's not even saying that it's throwing a pokeball like it used to, it only says it ran away like a bitch.

**Comment by BioMuell** [comment]
Did you check if you have Pokeballs?

**Comment by Lynical** [comment]
What the fuck, i had 150 pokeballs and now 0?

the fuck is dis lul, but it's not getting any balls from any pokestops but with the other version of your friend it used to get allot of pokeballs from pokestops.

something is wrong with your version, it's not displaying the messages if it got anything from the pokestop.

**Comment by BioMuell** [comment]
How many Items do you have?
The recycler is working.

**Comment by Lynical** [comment]
I have the recylcer disabled as I don't want it to recycle.

I never had it enabled either.

**Comment by BioMuell** [comment]
Thats the reason, you dont have enough space :p

**Comment by Sen66** [comment]
this can be the reason, maybe your inventory is full of potions and stuff so it cant get any more pokeballs.
thank you very much @BioMuell

**Comment by Lynical** [comment]
How can I upgrade my backpack without using pokecoins lol

and yes my inventory was 418/350

i need to know how to get my backpack bigger without wasting real money ;s

**Comment by Sen66** [comment]
You can set a minimum amount of stuff you want to keep of every item in the filter so it doesnt delete everything. That can help your problem. @Lynical

**Comment by Lynical** [comment]
yeah now everything works..

well fuck me for being so stupid, damnit pokemon go why is the space in the backpack so low ;(

**Comment by Sen66** [comment]
we both were so stupid lol. Why didnt we think about the backpack lol

**Comment by Lynical** [comment]
PS: Did you fix the DoNotTransfer bug?

**Comment by Lynical** [comment]
http://prntscr.com/bw8xf5 this one where you need to have 1 pokemon in the list otherwise it'll fuck up?

**Comment by Sen66** [comment]
wait a moment

**Comment by Sen66** [comment]
You use the "leaveStrongest" mode, right?

**Comment by Lynical** [comment]
Yes I do.

**Comment by Sen66** [comment]
Okay, the leaveStrongest mode refers to the function placed at line 329. You are editing the wrong array.

**Comment by Lynical** [comment]
you need to be more specific, i don't know what you mean ;s

**Comment by Lynical** [comment]
Im talking about this bug http://prntscr.com/bw938b

not this one http://prntscr.com/bw93cr

**Comment by Sen66** [comment]
Thats not really a bug in your function as the function in which is the bug isnt getting called.  the "leaveStrongest" mode uses another function. "TransferAllButStrongestUnwantedPokemon", thats the name of it. The pokemon in the "bug"-array arent affecting anything.

**Comment by Lynical** [comment]
Im talking about that I can't cross them all out, i need to have 1 pokemon in that list that doesnt have // infront of it, which annoys me as i want to have them all with //

**Comment by Sen66** [comment]
But why do you want all of them commented? They dont affect the way the bot works in "leaveStrongest" mode.

**Comment by Lynical** [comment]
Because I don't want any of these pokemons as they're shit.

**Comment by Sen66** [comment]
You dont understand D:
The function you refer to is NOT being called. Thats the wrong function for your mode. You have to set the pokemons you dont want etc. in the func. named "TransferAllButStrongestUnwantedPokemon"

**Comment by Lynical** [comment]
well then the function is still bugged as i still have those shit pokemons in my pokemons lol

http://prntscr.com/bw9bsu

**Comment by Sen66** [comment]
I havent made these functions and I'm using duplicate mode. Ill look later into this.
