### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by xDiglett** [Sen66/Pokemon-Go-Rocket-API#2]
![Errors](https://i.imgur.com/0ik0rmK.png)

Getting a nullpointer when launching

**Comment by xDiglett** [comment]
This seems to be happening when ptc server is down, can we make any kind of retry script?

**Comment by Sen66** [comment]
yes this would be possible. Looking into this asap.

**Comment by Sen66** [comment]
I commited generel exception handling.
