### ISSUE TITLE
Crashing when PTC login servers are down

### ISSUE THREAD

**Issue by unexpectedbukakke** [Sen66/Pokemon-Go-Rocket-API#3]
Currently the bot is still crashing if unable to login to the PTC servers (see https://github.com/Sen66/Pokemon-Go-Rocket-API/issues/2). 

Tested w/ latest build with commit pushed 5 minutes ago.

**Comment by Sen66** [comment]
lemme look into this.

**Comment by unexpectedbukakke** [comment]
Actually, scratch that, the program is not crashing though it is throwing a bunch of exceptions. http://www.hastebin.com/wakatitoqe.tex

**Comment by Sen66** [comment]
It shouldnt output that. I commited a fix(maybe?) for this that supresses the warning and outputs some proper error. Feel free to test it for me as I have no PTC account :^)

**Comment by unexpectedbukakke** [comment]
Seems to be outputting correctly now with the new commit.

Json Reader Exception - Server down? - Restarting
Argument Null Refference - Restarting

Thanks!

**Comment by Sen66** [comment]
When you get an error like 100 times in a row tell me please.
I help when I can :smile:
